### ISSUE TITLE
Proposed RP2040 pinout

### ISSUE THREAD

**Issue by MichaelBell** [TinyTapeout/tt-demo-pcb#1]
It would be good to define which RP2040 IOs were connected to which TT user project IOs before TT04 submissions close, so that TT04 projects can know which pins to interface with RP2040 peripherals on (e.g. SPI, UART, I2C and to a lesser extent, PIO).

My proposal for the pinout would be:
```
0   TT <- RP        Input 0
1   TT <- RP        Input 1
2   TT <- RP        Input 2
3   TT <- RP        Input 3
4   TT <- RP        Input 4
5   TT <- RP        Input 5
6   TT <- RP        Input 6
7   TT <- RP        Input 7
8   TT <-> RP       Bidi 0
9   TT <-> RP       Bidi 1
10  TT <-> RP       Bidi 2
11  TT <-> RP       Bidi 3
12  TT <-> RP       Bidi 4
13  TT <-> RP       Bidi 5
14  TT <-> RP       Bidi 6
15  TT <-> RP       Bidi 7
16  TT  -> RP       Output 0
17  TT  -> RP       Output 1
18  TT  -> RP       Output 2
19  TT  -> RP       Output 3
20  TT  -> RP       Output 4
21  TT  -> RP       Output 5
22  TT  -> RP       Output 6
23  TT  -> RP       Output 7
24  Clock Output    CLK
25  Reset           RST_N
26  Controller      SEL_RST_N
27  Controller      SEL_INC
28  Controller      ENA
29  Other           LED
```

Considerations:
- For PIO, useful to be able to use contiguous blocks of pins on RP2040, so arrange the user project IOs contiguously in some order, and have the bidi IOs between the fixed direction IOs so you have the possibility of 16 contiguous inputs or outputs.
- For SPI, SPI0 is available on GPIOs 0-7, 16-23.  SPI1 is available on GPIOs 8-15, 24-29 so with this ordering both can be used (SPI0 through the fixed direction IOs, SPI1 through the bidirectional IOs).
- The UART and I2C repeat in blocks of 8 and 4 respectively, so aligning with those boundaries is sensible
- GPIOs 26-29 should not have voltage applied when the RP2040 is unpowered.  If the board has an option not to power the RP2040 these could be protected with diodes and any added delay/switching frequency concerns should not matter as those signals are not connected to the user project.

**Comment by urish** [comment]
@psychogenic FIY

**Comment by urish** [comment]
Note: we may also need a way to interface with Caravel's house keeping SPI.

Perhaps the controller ENA can double as chip select for the house keeping SPI, and some of the input/bidi pins can be used for tL remaining SPI signals

**Comment by urish** [comment]
Update: bidir pins can't easily be used for this purpose, as they have an undefined digital state (i.e. they can be outputs) when no design is selected.

**Comment by urish** [comment]
Closing as this was discussed on discord
