### ISSUE TITLE
fix 1.8v power led brightness

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-demo-pcb#10]
use a mosfet to drive the led

**Comment by psychogenic** [comment]
Done, added a FET and feeding from 3v3.  Series term on gate using value we already have on the board.  Have a range of options on the specific nfet, set the LCSC number to C2891732 (basically an si2302 dirt cheap type deal).
![switchedled](https://github.com/TinyTapeout/tt-demo-pcb/assets/1799255/b2762c9d-2bec-400f-b859-4cbb09c8127f)
