### ISSUE TITLE
current measure header and 1.8 override

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-demo-pcb#11]
The current method of measuring core current is to remove resistor and place a header. I would like the header to be replaced with a standard 2.54 mm pitch.

Also I would like an easy way to provide 1.8 from another source. Perhaps adding an additional gnd hole so that once the resistor is removed a 3 pin header can be placed ?

**Comment by psychogenic** [comment]
Ok, replaced header with 100mil version and moved things around (blue arrow).  If you want to power with your own 1v8, remove that same R49 (blue slash) and power through headers indicated in red.  ![1v8powering](https://github.com/TinyTapeout/tt-demo-pcb/assets/1799255/e2f58af2-65af-4bc8-bfe8-fa408e77896c)

**Comment by mattvenn** [comment]
Thanks!
