### ISSUE TITLE
Manual clock 1-step function RC network design area review request

### ISSUE THREAD

**Issue by dlmiles** [TinyTapeout/tt-demo-pcb#3]
Please review the use of R7/R12/C1 around the manual clock 1-step function.

The concern is in relation to the impact of RC circuit on the signal integrity of the `project_clk` line which is an important aspect to many projects.  Especially as the clock rate is increased through the MHz, towards 50MHz planned max RP2040 and 66MHz the documented max sky130 IO input rate (maybe 66MHz should be the PCB design limit for any computations, for example if someone attaches their own clock source while the RP2040 pin is tri-state/HiZ).

In particular it would be ideal to validate and measure (possibly with a breadboard setup) how the signal changes at a variety of clock frequencies.  Also the shape of the signal from the button use.  Possibly also against a misconfigurated RP2040 also trying to provide a stable output.

Maybe a reduction of C1 (100nF) to a smaller value turns out to meet requirements ?

@MichaelBell suggested an additional resistor between C1/R12 junction and project_clk net may also resolve concerns.

Other thoughts in the area:
 * consideration to using GPIO29 (if unused) to connect the clock 1-step switch to this GPIO only, make project_clk driven only by the RP2040 firmware and the removal of any extra capacitance on the project_clk net.  This might have other benefits, a button able to communicate with RP2040 firmware directly opens up other project possibilities?
 * if GPIO29 is possible, potential to leave unpopulated option in PCB design to `relink` manual clock switch back to project_clk (with the customer using a 1x2 header pin + jumper) where the track near R12<>project_clk was disconnected.
 * confirmation if an RC debounce approach is enough to provide intended project reliability to students for edge triggered flopflops, some people might consider a schmitt-trigger to provide output to project_clk line from a switch+RC to be the minimum approach

Related discord discussion area links:
https://discord.com/channels/1009193568256135208/1009395924017086475/1167335321365651496
https://discord.com/channels/1009193568256135208/1011201396659474432/1167393079456714783

**Comment by mattvenn** [comment]
resolved
