### ISSUE TITLE
add a reference for the 7 seg display

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-demo-pcb#9]
to help answer the question - what is segment A?
on the back there is a nice table, I suggest adding a picture with each segment labelled.

**Comment by psychogenic** [comment]
Done, added this next to table ![7seghelp](https://github.com/TinyTapeout/tt-demo-pcb/assets/1799255/2752d46f-7d3a-4886-99f1-ae56bd65374c)

**Comment by psychogenic** [comment]
Tell me if it needs mods, but closing this.
